{% set version = "7.1.2" %}

package:
  name: balsamic
  version: {{ version }}

source:
  url: "https://github.com/Clinical-Genomics/BALSAMIC/archive/v{{ version }}.tar.gz"
  sha256: 712f3047a15e21db673142285e57e1b7a18ec3871e9b50a1f4e751f3d5ba0c60

build:
  noarch: python
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  host:
    - python ==3.6
    - pip
  run:
    - python ==3.6

test:
  imports:
    - snakemake
    - BALSAMIC

about:
  home: https://github.com/Clinical-Genomics/BALSAMIC 
  license: MIT
  summary: Bioinformatic analysis pipeline for somatic mutations using high-throughput sequencing data
